package main

import (
	"fmt"
	"net/http"
)

func main() {
	http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		html := `
		<!DOCTYPE html>
		<html>
		<head>
			<title>Hello, Go Web</title>
		</head>
		<body>
			<h1>Hello, Go Web!</h1>
			<p>This is a simple HTML page generated by Go.</p>
		</body>
		</html>
		`

		fmt.Fprintln(w, html)
	})

	http.ListenAndServe(":3000", nil)
}
